// 이 파일은 scripts/sync-achievements.js 로 자동 생성됩니다.
// 직접 수정하지 말고 노션에서 수정 후 다시 동기화하세요.
const ACHIEVEMENT_CARDS = [
  {category:"모르가나", point:2, text:"저승사자를 봤다는 소문이 도았다."},
  {category:"테탈로스", point:2, text:"항해 중 무인도에 표류했다가 구조되었다."},
  {category:"골드하임", point:2, text:"숨겨진 보물을 찾아냈다."},
  {category:"네크로시스", point:1, text:"마을에 도는 소문난 병을 용케 피해갔다."},
  {category:"네크로시스", point:2, text:"전염병 확산을 막기 위해 격리소를 지켰다."},
  {category:"모르가나", point:1, text:"오래된 무덤가를 서성이고했다."},
  {category:"골드하임", point:1, text:"작은 장사로 푸돈을 모았다."},
  {category:"네크로시스", point:3, text:"저주받은 역병을 몸에 지니 채 살아갔다."},
  {category:"네크로시스", point:1, text:"병든 이웃을 돌보다 몸살을 압았다."},
  {category:"골드하임", point:3, text:"황금에 눈이 멀어 파멸을 자초했다."},
  {category:"테탈로스", point:2, text:"바다의 전설을 좋아 먼 항해를 떠났다."},
  {category:"네크로시스", point:2, text:"병든 이들을 위해 몰래 약초를 나눠주었다."},
  {category:"골드하임", point:2, text:"욕심에 눈이 멀어 친구를 배신했다."},
  {category:"테탈로스", point:3, text:"대양을 건너 최초의 인물이 되었다."},
  {category:"모르가나", point:3, text:"사경을 햤매다 기적처럼 되살아났다."},
  {category:"네크로시스", point:2, text:"역병에 걸렸으나 홀로 이겨냈다."},
  {category:"네크로시스", point:3, text:"온 마을을 휘쓠 역병에서 유일하게 살아남았다."},
  {category:"테탈로스", point:3, text:"바다의 왕이라 불리는 해적단을 이끌었다."},
  {category:"골드하임", point:3, text:"왕국 하나를 살 수 있을 만큼의 부를 쌓았다."},
  {category:"골드하임", point:1, text:"우연히 동전 몇 닙을 주웠다."},
  {category:"테탈로스", point:2, text:"해적선과의 싸움에서 살아남았다."},
  {category:"모르가나", point:3, text:"산 자와 죽은 자의 경계에서 길잡이가 되었다."},
  {category:"테탈로스", point:1, text:"폭풍우 치던 바다에서 살아남았다."},
  {category:"골드하임", point:1, text:"도박에서 소소하게 따다."},
  {category:"모르가나", point:1, text:"가까운 이의 임종을 지켰다."},
  {category:"테탈로스", point:1, text:"해안가에서 낯선 조개를 주웠다."},
  {category:"모르가나", point:1, text:"죽음의 문턱까지 갔다가 돌아왔다."},
  {category:"테탈로스", point:1, text:"처음으로 배를 타고 바다에 나갔다."},
  {category:"모르가나", point:2, text:"죽음을 두려워하지 않게 되었다."},
  {category:"네크로시스", point:1, text:"이상한 발진이 온옴에 돋았으나 곳 가라앉았다."},
  {category:"골드하임", point:2, text:"큰 거래를 성사시켜 부를 쌓았다."},
  {category:"골드하임", point:3, text:"전설의 보물을 손에 넣었다."},
  {category:"모르가나", point:2, text:"죽은 자를 거두는 일을 도맡았다."},
  {category:"네크로시스", point:3, text:"역병의 근원을 찾아내 마을을 구했다."},
  {category:"모르가나", point:3, text:"죽음의 신과 거래를 했다는 소문이 도았다."},
  {category:"테탈로스", point:3, text:"전설의 바다괴물과 마주치고도 살아남았다."},
  {category:"하이란", point:3, text:"대를 이을 후계자를 훌륭히 키워냈다."},
  {category:"바르돈", point:2, text:"유명한 결투에서 승리해 이름을 알렸다."},
  {category:"그라쉬", point:2, text:"산적으로 활동하며 여러 악행을 저질렀다."},
  {category:"그라쉬", point:2, text:"뒷골목 조직을 이끌며 세력을 넓혔다."},
  {category:"셀루나", point:1, text:"작은 발명품을 만들었다."},
  {category:"하이란", point:3, text:"원수 집안과 혼인을 성사시켜 오랜 반목을 끝냈다."},
  {category:"바르돈", point:3, text:"불가능하다던 전쟁을 승리로 이끌었다."},
  {category:"하이란", point:1, text:"오랜 친구를 다시 만났다."},
  {category:"그라쉬", point:2, text:"무고한 이를 모함해 파멸시켰다."},
  {category:"오블리비아", point:1, text:"낯선 예언자에게 알 수 없는 말을 들었다."},
  {category:"셀루나", point:2, text:"실전된 기술을 재현했다."},
  {category:"바르돈", point:1, text:"맹수 한 마리를 홀로 처치했다."},
  {category:"그라쉬", point:1, text:"남의 물건에 손을 댔다."},
  {category:"셀루나", point:3, text:"시대를 앞선 발명으로 세상을 바꿨다."},
  {category:"오블리비아", point:3, text:"봉인된 재앙을 막아냈다."},
  {category:"하이란", point:1, text:"이웃과 소소한 정을 나눴다."},
  {category:"오블리비아", point:3, text:"신의 계시를 받았다고 전해진다."},
  {category:"그라쉬", point:3, text:"죄 없는 이들을 팔아넘겨 부를 쌓았다."},
  {category:"하이란", point:3, text:"멸문한 가문을 재건했다."},
  {category:"오블리비아", point:1, text:"우연히 오래된 유물을 주웠다."},
  {category:"오블리비아", point:2, text:"정체 모를 존재와 계약을 맺었다."},
  {category:"바르돈", point:3, text:"단신으로 성 하나를 함락시켰다."},
  {category:"그라쉬", point:1, text:"사소한 시비에 칼을 뽑았다."},
  {category:"하이란", point:2, text:"첫사랑과 재회해 여생을 함께했다."},
  {category:"바르돈", point:1, text:"첫 전투에서 살아남았다."},
  {category:"오블리비아", point:1, text:"이상한 꿈을 자주 꿨다."},
  {category:"하이란", point:2, text:"버림받은 아이를 거두어 키웠다."},
  {category:"그라쉬", point:3, text:"마을 하나를 몰살시켰다."},
  {category:"그라쉬", point:1, text:"술김에 주먹다짐을 벌였다."},
  {category:"하이란", point:1, text:"자식을 낳았다."},
  {category:"바르돈", point:1, text:"훈련 시합에서 이름을 알렸다."},
  {category:"바르돈", point:2, text:"부대를 이끌고 전투에서 승리했다."},
  {category:"그라쉬", point:3, text:"왕의 목숨을 노린 암살을 주도했다."},
  {category:"바르돈", point:3, text:"전쟁에서 적장을 죽여 영웅이 되었다."},
  {category:"하이란", point:2, text:"원수와 화해했다."},
  {category:"오블리비아", point:2, text:"저주를 스스로 풀었다."},
  {category:"셀루나", point:1, text:"마을 아이들에게 글을 가르쳤다."},
  {category:"오블리비아", point:2, text:"잊혀진 의식을 되살렸다."},
  {category:"셀루나", point:3, text:"후대에 남을 학문을 세웠다."},
  {category:"셀루나", point:2, text:"새로운 치료법을 개발해 많은 이를 살렸다."},
  {category:"셀루나", point:2, text:"난제로 불리던 문제를 풀어냈다."},
  {category:"셀루나", point:3, text:"왕국의 운명을 가른 계책을 세웠다."},
  {category:"바르돈", point:2, text:"포위망을 뚫고 동료들을 구해냈다."},
  {category:"오블리비아", point:3, text:"죽음의 문턱에서 돌아와 예언자가 되었다."},
  {category:"셀루나", point:1, text:"오래된 기록을 정리했다."},
];
